export const RESTAURENT_STORE_UPDATE_BY_KEY =
  'restaurent/RESTAURENT_STORE_UPDATE_BY_KEY';
export const FETCH_ITEM_BY_ID = 'restaurent/FETCH_ITEM_BY_ID';
export const FETCH_CUSTOMER_BROUGHT_ITEM =
  'restaurent/FETCH_CUSTOMER_BROUGHT_ITEM';
