export const UPDATE_MAA_KE_HATH_KA_DATA = 'UPDATE_MAA_KE_HATH_KA_DATA';
export const VALIDATE_DFH_CITY = 'VALIDATE_DFH_CITY';
export const ADD_TO_DFH_CART = "ADD_TO_DFH_CART";
export const VALIDATE_DFH ="VALIDATE_DFH"