import React, { useContext } from 'react';
import { makeStyles, Box, Button, Typography } from '@material-ui/core';
import { HistoryContext } from 'containers/App/HistoryContext';
import icon from '../../images/policy.png';

const useStyles = makeStyles(theme => ({
  appWrapper: {
    maxWidth: 1064,
    margin: '40px auto 0',
    width: '100%',
    overflow: 'hidden',
    padding: '0 40px 40px',
    [theme.breakpoints.down('sm')]: {
      margin: '20px auto',
      padding: '0 20px',
    },
  },
  heading: {
    fontSize: 35,
    fontWeight: 700,
    marginLeft: 10,
  },
  policyContent: {
    '& h3': {
      marginBottom: '0',
      textTransform: 'capitalize',
    },
    '& .alpha': {
      listStyleType: 'lower-alpha',
    },
    '& .number': {
      listStyleType: 'decimal',
    },
    '& .roman': {
      listStyleType: 'upper-roman',
    },
    '& ul': {
      padding: '0 0 0 17px',
      '& li': {
        marginBottom: '16px',
        fontSize: '14px',
        textAlign: 'justify',
        lineHeight: '1.5',
      },
    },
    '& p': {
      marginBottom: '16px',
      fontSize: '14px',
      textAlign: 'justify',
      lineHeight: '1.5',
    },
  },
  desc: {
    fontSize: 20,
  },
}));

const PrivacyPolicy = () => {
  const classes = useStyles();
  const { history } = useContext(HistoryContext);
  return (
    <div className={classes.appWrapper}>
      <Box
        display="flex"
        alignItems="center"
        pb={2}
        mb={6}
        style={{ borderBottom: '1px solid #000' }}
      >
        <img src={icon} alt="Terms Icon" height="47px" width="47px" />
        <div className={classes.heading}>PRIVACY POLICY</div>
      </Box>
      <div className={classes.policyContent}>
        <h3>1. General</h3>
        <ul className="alpha">
          <li>
            This document is an electronic record in terms of Information
            Technology Amendment Act, 2008 and rules there under as applicable
            and the amended provisions pertaining to electronic various statutes
            as amended by the Information Technology Amendment Act, 2008. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </li>
          <li>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of
            https://justmyroots.com.
          </li>
          <li>
            This Privacy Policy (‘Policy’) constitutes a binding contract
            between customer (“you/ your/ user”) and Createcomm Tech Pvt. Ltd.
            (“Createcomm/ us/ our/ we”) with regard to your use of its website
            www.justmyroots.com/ www.Createcomm.com or Mobile Application (“website”) and the use of
            various services (“contracted services/ interstate food
            distribution/ food delivery”) provided by us. It is clarified that
            by using the website or by availing the contracted services it
            constitutes an acknowledgment and acceptance of the terms.
          </li>
          <li>
            The terms ‘Party’ and ‘Parties’ shall respectively be used to refer
            to the customer and Createcomm individually and collectively, as the
            context so requires.
          </li>
          <li>
            The headings of each section in this Policy are only for the purpose
            of organizing the various provisions under this Policy in an orderly
            manner, and shall not be used by either Party to interpret the
            provisions contained herein in any manner. Further, it is
            specifically agreed to by the Parties that the headings shall have
            no legal or contractual value.
          </li>

          <li>
            The use of the Website by the User is solely governed by this Policy
            as well as the Terms of Use of the Website and any modifications or amendments made thereto by the Company
            from time to time, at its sole discretion. Visiting the home page of
            the Website and/or using any of the services provided on the Website
            shall be deemed to signify the User’s unequivocal acceptance of this
            Policy and the aforementioned Terms, and the User expressly agrees
            to be bound by the same. The User expressly agrees and acknowledges
            that the Terms and Policy are co-terminus, and that expiry /
            termination of either one will lead to the termination of the other.
          </li>

          <li>
            The User unequivocally agrees that this Policy and the
            aforementioned Terms constitute a legally binding agreement between
            the User and the Company, and that the User shall be subject to the
            rules, guidelines, policies, terms, and conditions applicable to any
            service that is provided by the Website, and that the same shall be
            deemed to be incorporated into the Terms and shall be treated as
            part and parcel of the same. The User acknowledges and agrees that
            no signature or express act is required to make these Terms and the
            Policy binding on the User, and that the User’s act of visiting any
            part of the Website constitutes the User’s full and final acceptance
            of the Policy and the aforementioned Terms.
          </li>

          <li>
            The Parties expressly agree that the Company retains the sole and
            exclusive right to amend or modify the Policy and the aforementioned
            Terms without any prior permission or intimation to the User, and
            the User expressly agrees that any such amendments or modifications
            shall come into effect immediately. The User has a duty to
            periodically check the Policy and Terms and stay updated on their
            provisions and requirements. If the User continues to use the
            Website following such a change, the User will be deemed to have
            consented to any and all amendments / modifications made to the
            Policy and Terms. In so far as the User complies with the Policy and
            Terms, he/she is granted a personal, non-exclusive,
            non-transferable, revocable, limited privilege to enter, access and
            use the Website.
          </li>
        </ul>
        <h3>2. Collection of personal and other information</h3>
        <ul className="alpha">
          <li>
            The User expressly agrees and acknowledges that the Company collects
            and stores the User’s personal information, which is provided by the
            User from time to time on the Website, including but not limited to
            the User’s user name, passwords, email address, name, address, date
            of birth, sex, nationality, shopping preferences, browsing history,
            etc., as well as any images or other information uploaded/published
            by the User on the Website.The User is aware that this information
            will be used by the Company/Website to provide services and features
            targeted at the User, that are most likely to meet the User’s needs,
            and also to customize and improve the Website to make its users’
            experiences safer and easier.
          </li>

          <li>
            The User is aware that the Company/Website may automatically track
            certain information about the User based upon the User’s IP address
            and the User’s behaviour on the Website, and the User expressly
            consents to the same. The User is aware that this information is
            used to do internal research on user demographics, interests, and
            behaviour, to enable the Company/Website to better understand, and
            cater to the interests of its users. The User is expressly made
            aware that such information may include the URL that the User
            visited prior to accessing the Website, the URL which the User
            subsequently visits (whether or not these URLs form a part of the
            Website), the User’s computer &amp; web browser information, the
            User’s IP address, etc.
          </li>

          <li>
            If the User chooses to purchase products / services from the
            Website, the User consents to allowing the Company/Website to
            collect information about the User’s buying behaviour and
          </li>

          <li>
            If the User chooses to post messages / reviews / feedback anywhere
            on the Website, including but not limited to message boards, chat
            rooms, other message areas, etc., the User is aware that any and all
            such information provided/ uploaded will be collected and stored by
            the the Company indefinitely, and that such retained information may
            be used to resolve disputes, provide customer support, troubleshoot
            problems, etc., and that such information, if requested, may be
            provided to judicial or governmental authorities of requisite
            jurisdiction, or otherwise used by the Company/Website as permitted
            by applicable laws.
          </li>

          <li>
            The User is aware that any and all information pertaining to the
            User collected by the Company, whether or not directly provided by
            the User to the Company/Website, including but not limited to
            personal correspondence such as emails or letters, feedback from
            other users or third parties regarding the User’s activities or
            postings on the Website, etc., may be collected and compiled by the
            Company/Website into a file/folder specifically created for /
            allotted to the User, and the User hereby expressly consents to the
            same.
          </li>

          <li>
            The User is aware that while he/she can browse some sections of the
            Website without being a registered user, certain activities (such as
            placing an order) require the User to provide valid information to
            the Company/Website for the purpose of registration. The User is
            aware that the contact information provided to the Company/Website
            may be used to send the User offers and promotions, whether or not
            based on the User’s previous orders and interests, and the User
            hereby expressly consents to receiving the same.
          </li>

          <li>
            The User is aware that the Company/Website may occasionally request
            the User to complete optional online surveys. These surveys may
            require the User to provide contact information and demographic
            information (like zip code, age, income bracket, sex, etc.). The
            User is aware that this data to is used to customise the Website for
            the benefit of the User, and providing all users of the Website with
            products/services/content that the Company/Website believes they
            might be interested in availing of, and also to display content
            according to the User’s preferences.
          </li>
          <li>
            The User is further aware that the Company/Website may occasionally
            request the User to write reviews for products/services
            purchased/availed of by the User from the Website, and also reviews
            for the various sellers listing their products/services on the
            Website. The User is aware that such reviews will help other users
            of the website make prudent and correct purchases, and also help the
            Company/Website remove sellers whose products are unsatisfactory in
            any way, and the User hereby expressly authorises the
            Company/Website to publish any and all reviews written by the User
            on the Website, along with the User’s name and certain contact
            details, for the benefit and use of other Users of the Website.
          </li>
          <li>
            Nothing contained herein shall be deemed to compel the
            Website/Company to store, upload, publish, or display in any manner
            content/reviews/surveys/feedback submitted by the User, and the User
            hereby expressly authorises the Website/Company to remove from the
            Website Website any such content, review, survey, or feedback
            submitted by the User, without cause or being required to notify the
            User of the same.
          </li>
        </ul>
        <h3>3. Cookies</h3>
        <ul className="alpha">
          <li>
            The User expressly agrees and acknowledges that the Company collects
            and stores the User’s personal information, which is provided by the
            User from time to time on the Website, including but not limited to
            the User’s user name, passwords, email address, name, address, date
            of birth, sex, nationality, shopping preferences, browsing history,
            etc., as well as any images or other information uploaded/published
            by the User on the Website.The User is aware that this information
            will be used by the Company/Website to provide services and features
            targeted at the User, that are most likely to meet the User’s needs,
            and also to customize and improve the Website to make its users’
            experiences safer and easier.
          </li>
          <li>
            The User is aware that a ‘Cookie’ is a small piece of information
            stored by a web server on a web browser so it can later be traced
            back from that particular browser, and that cookies are useful for
            enabling the browser to remember information specific to a given
            user, including but not limited to a user’s login identification,
            password, etc. The User is aware that the Website places both
            permanent and temporary cookies in the User’s computer’s hard drive
            and web browser and does hereby expressly consent to the same.
          </li>

          <li>
            The User is further aware that the Website uses data collection
            devices such as cookies on certain pages of the Website to help
            analyse web page flow, measure promotional effectiveness, and
            promote trust and safety, and that certain features of the Website
            are only available through the use of such cookies. While the User
            is free to decline the Website’s cookies if the User’s browser
            permits, the User may consequently be unable to use certain features
            on the Website
          </li>

          <li>
            Additionally, the User is aware that he/she might encounter
            ‘cookies’ or other similar devices on certain pages of the Website
            that are placed by third parties or affiliates of the
            Company/Website. The User expressly agrees and acknowledges that the
            Company/Website does not control the use of such cookies/other
            devices by third parties, that the Company/Website is in no way
            responsible for the same, and that the User assumes any and all
            risks in this regard.
          </li>
        </ul>
        <h3>4. Divulging/Sharing of personal information</h3>
        <ul className="alpha">
          <li>
            The User is aware that the Website/Company may share the User’s
            personal information with other corporate entities and affiliates to
            help detect and prevent identity theft, fraud and other potentially
            illegal acts; correlate related or multiple accounts to prevent
            abuse of the Website’s services; and to facilitate joint or
            co-branded services, where such services are provided by more than
            one corporate entity.
          </li>

          <li>
            The User is aware that the Website/Company may disclose personal
            information if required to do so by law or if the Website/Company in
            good faith believes that such disclosure is reasonably necessary to
            respond to subpoenas, court orders, or other legal processes. The
            Website/Company may also disclose the User’s personal information to
            law enforcement offices, third party rights owners, or other third
            parties if it believes that such disclosure is reasonably necessary
            to enforce the Terms or Policy; respond to claims that an
            advertisement, posting or other content violates the rights of a
            third party; or protect the rights, property or personal safety of
            its users, or the general public.
          </li>

          <li>
            The User is further aware that the Website/Company and its
            affiliates may share / sell some or all of the User’s personal
            information with other business entities should the Company/Website
            (or its assets) plan to merge with, or be acquired by such business
            entity, or in the event of reorganization, amalgamation, or
            restructuring of the Company’s business. Such business entity or new
            entity will continue to be bound by the Terms and Policy, as may be
            amended from time to time.
          </li>
        </ul>
        <h3>5. Security</h3>
        <p>
          Transactions on the Website are secure and protected. Any information
          entered by the User when transacting on the Website is encrypted to
          protect the User against unintentional disclosure to third parties.
          The User’s credit and debit card information is not received, stored
          by or retained by the Company / Website in any manner. This
          information is supplied by the User directly to the relevant payment
          gateway which is authorized to handle the information provided, and is
          compliant with the regulations and requirements of various banks and
          institutions and payment franchisees that it is associated with.
        </p>

        <h3>6. Third party Advertisement / Promotions </h3>
        <p>
          The User is aware that the Company/Website uses third-party
          advertising companies to serve ads to the users of the Website. The
          User is aware that these companies may use information relating to the
          User’s visits to the Website and other websites in order to provide
          customised advertisements to the User. Furthermore, the Website may
          contain links to other websites that may collect personally
          identifiable information about the User. The Company/Website is not
          responsible for the privacy practices or the content of any of the
          aforementioned linked websites, and the User expressly acknowledges
          the same and agrees that any and all risks associated will be borne
          entirely by the User.
        </p>

        <h3>7. User's Consent</h3>
        <p>
          By using the Website and/ or by providing information to the Company
          through the Website, the User consents to the collection and use of
          the information disclosed by the User on the Website in accordance
          with this Policy, including but not limited to the User’s consent the
          Company/Website sharing/divulging the User’s information, as per the
          terms contained hereinabove in Section 4 of the Policy.
        </p>

        
        <h3>8. Account Deletion & Data Erasure </h3>
        <p>
        If you wish to delete your account with us or erase sensitive information, you may send us an email to the effect at care@justmyroots.com mentioning your relevant account information and we shall process the request on our end. We shall send you a confirmation email once your account and/or data is permanently deleted from our system.
        </p>
        <h3>9. Grievance Officer </h3>
        <p>
          In accordance with Information Technology Act 2000 and rules made
          there under, the name and email details of the Grievance Officer are
          provided below:
        </p>
        <p>
          <strong>Rajan Sachdeva – </strong>{' '}
          <a href="mailto:rajan@raas.org.in">rajan@raas.org.in</a>
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
