import React, { useContext } from 'react';
import { makeStyles, Box, Button, Typography } from '@material-ui/core';
import { HistoryContext } from 'containers/App/HistoryContext';
import icon from '../../images/terms.png';

const useStyles = makeStyles(theme => ({
  appWrapper: {
    maxWidth: 1064,
    margin: '50px auto 0',
    width: '100%',
    overflow: 'hidden',
    padding: '0 40px 40px',
    [theme.breakpoints.down('sm')]: {
      margin: '20px auto',
      padding: '0 20px',
    },
  },
  heading: {
    fontSize: 35,
    fontWeight: 700,
    marginLeft: 10,
  },
  policyContent: {
    '& h3': {
      marginBottom: '0',
      textTransform: 'capitalize',
    },
    '& .alpha': {
      listStyleType: 'lower-alpha',
    },
    '& .number': {
      listStyleType: 'decimal',
    },
    '& .roman': {
      listStyleType: 'upper-roman',
    },
    '& ul': {
      padding: '0 0 0 17px',
      '& li': {
        marginBottom: '16px',
        fontSize: '14px',
        textAlign: 'justify',
        lineHeight: '1.5',
      },
    },
    '& p': {
      marginBottom: '16px',
      fontSize: '14px',
      textAlign: 'justify',
      lineHeight: '1.5',
    },
  },
  desc: {
    fontSize: 20,
  },
}));

const Terms = () => {
  const classes = useStyles();
  const { history } = useContext(HistoryContext);
  return (
    <div className={classes.appWrapper}>
      <Box
        display="flex"
        alignItems="center"
        pb={2}
        mb={6}
        style={{ borderBottom: '1px solid #000' }}
      >
        <img src={icon} alt="Terms Icon" height="47px" width="47px" />
        <div className={classes.heading}>TERMS AND CONDITIONS</div>
      </Box>
      <div className={classes.policyContent}>
        <h3>General</h3>
        <p>
          In terms of Information Technology Act, 2000, this document is an
          electronic record. Being generated by a computer system it does not
          require any physical or digital signatures. This document is published
          in accordance with the provisions of Rule 3 (1) of the Information
          Technology (Intermediaries guidelines) Rules, 2011 that require
          publishing the rules and regulations, privacy policy and Terms of Use
          for access or usage of Create Comm Tech Pvt Ltd
        </p>
        <ul className="dot">
          <li>
            The domain name www.justmyroots.com & or Mobile Application (hereinafter referred to as
            &quot;Website&quot;) is owned by Createcomm Tech Pvt. Ltd., a
            Private Company incorporated under the Companies Act 2013 (including
            without limitation any amendments/subsequent legislations), having
            its registered office at 1207, 12 th Floor, Unitech Signature
            Towers, Block-B, South City-I, Block-L, Sector-30, Gurgaon,
            Haryana-122001, where such expression shall, unless repugnant to the
            context thereof, be deemed to include its respective legal heirs,
            representatives, administrators, permitted successors and assigns.
          </li>
          <li>
            For the purpose of these Terms of Use, wherever the context so
            requires &quot;You&quot; or &quot;User&quot; shall mean any natural
            or legal person who accesses the Website. The term &quot;We&quot;,
            &quot;Us&quot;, &quot;Our&quot; shall mean Createcomm Tech Pvt. Ltd.
            The headings of each section in this Agreement are only for the
            purpose of organising the various provisions under this Agreement in
            an orderly manner. These headings shall not be used by either party
            to interpret the provisions contained with them in any manner.
            Further, the heading has no legal or contractual value.
          </li>

          <li>
            The use of this Website by You is solely governed by this policy and
            any policy so mentioned by terms of reference. Moving past home page
            or using any of the services shall be taken to mean that You have
            read and agreed to be bound by all of the policies. You will be
            subject to the rules, guidelines, policies, terms, and conditions
            applicable to any service that is provided by this site, and they
            shall be deemed to be incorporated into this Terms of Use and shall
            be considered as part and parcel of this terms of use.
          </li>

          <li>
            We hold the sole right to modify the Terms of Service without prior
            permission from You or informing You. The relationship creates on
            You a duty to periodically check the terms and stay updated on its
            requirements. If You continue to use the website following such a
            change, this is deemed as consent by You to the so amended policies.
            As long as You comply with these Terms of Use, we grant You a
            personal, non-exclusive, non-transferable, limited privilege to
            enter and use the Website.
          </li>
        </ul>
        <h3>Membership</h3>
        <p>
          To fully avail the services of the Website, registration is required.
          The use of this website is not limited to those above the age of 18
          only and are applicable to all barring those ‘Incompetent to Contract’
          which inter alia include insolvents under the Indian Contract Act,
          1872. Further, at any time during Your use of this Website, including
          but not limited to the time of registration, You are solely
          responsible for protecting the confidentiality of Your username and
          password, and any activity under the account shall be deemed to have
          been done by You. In the case that You provide Us with false and/or
          inaccurate details or the Website has reason to believe You have done
          so, We hold the right to permanently suspend your account.
        </p>

        <h3>Communications</h3>
        <p>
          By using this Website, it is deemed that you have consented to
          receiving calls, autodialed and/or pre-recorded message calls, from Us
          at any time with the use of the telephone that has been provided by
          you for the use of this website which are subject to the Privacy
          Policy. This includes contacting you through information received
          through other parties. The use of this website is also your consent to
          receive SMSs from US at any time we deem fit. This consent to be
          contacted is for purposes that include and are not limited to
          clarification calls and marketing and promotional calls. In case you
          wish to stop contact from Us for the same, you may send us a mail to
          the effect at{' '}
          <a href="mailto:care@justmyroots.com">care@justmyroots.com</a>
        </p>
        <p>
          You may also be contacted by Service Providers with whom we have
          entered into a contract in furtherance of our rights, duties and
          obligations under this documents and all other policies followed by
          Us. Such contact will be made only in pursuance of such objectives,
          and no other calls will be made.
        </p>

        <h3>Divulging/Sharing of personal information</h3>
        <ul className="dot">
          <li>
            The sharing of the information provided by you will governed by the
            Privacy Policy and We will not give out such contact information of
            yours to third parties not connected with the Website. The Website
            is a platform that Users utilize to meet and interact with one
            another for their transactions. We are not a party to such
            interaction and take no liability that arises from any such
            communication.
            <br />
            All communication which inter alia include the contract, its terms,
            your obligations, the sellers obligations, prices, etc., are
            outcomes of the communication between the seller and You. This
            includes, without any limitation, the prices, shipping costs,
            payment details, date, period and mode of delivery, warranties
            related to products and services and after sales services related to
            products and services. We do not have any control over such
            information and play no determinative role in the finalization of
            the same and hence do not stand liable for the outcomes of such
            communication.
          </li>

          <li>
            We do not endorse any of the products offered for sale on the
            website nor place any guarantee as to its nature, price, quality,
            etc.
          </li>

          <li>
            Subject to the above sub-clauses, a contract exists between the
            seller and the buyer and as such any breach of contract and thus,
            any claim arising from such breach is the subject matter of the
            seller and the buyer alone and we are in no way a party to such
            breach or involved in any suit arising from the same breach. The
            contact/communication arising from such breach may entail between
            the seller and the buyer directly without Us being involved.
          </li>
          <li>
            As the buyer, you are expected to check the creditworthiness of the
            seller and the genuineness of the products offered by them. While we
            do test the same at our end, however we are not liable for the same.
          </li>
          <li>
            The goods are in our possession for a limited time only for
            Delivery. At no point of time, the internal original packaging is
            tampered with. We only strengthen packaging from outside
          </li>
          <li>
            JMR takes responsibility of the products that we deliver. We have
            contracts with the Vendor which allows us to ask for replacement if
            the product quality is verified within a particular window. For all
            Perishable items, it is mandatory for the Customer to inform us (by
            E-mail, WhatsApp or a phone call) within 2 hrs of receiving the
            products about the quality of the product beyond which JMR does not
            take any responsibility. Customer would be required to take pictures
            of the product and keep for future reference. To understand the
            return and refund, please refer the Return and Refund Policy on our
            Website.
          </li>
          <li>
            You release and indemnify Us and/or any of its officers and
            representatives from any cost, damage, liability or other
            consequence of any of the actions of the Users of the Website and
            specifically waive any claims that you may have in this behalf under
            any applicable law. Please note that there could be risks in dealing
            with underage persons or people acting under false pretence.
          </li>
        </ul>
        <h3>Charges</h3>
        <p>
          The membership of this website is free of cost, and this includes the
          browsing of the site and the use of the services. However, we reserve
          the right to amend this no-fee policy and charge for the services
          rendered. In a case that such happens, Users will be intimated of the
          same, and it will be up to you to decide whether or not you will
          continue with services offered by us. Such changes are effective as
          soon as they are posted on the Site.
        </p>

        <h3>User Obligations</h3>
        <ul className="dot">
          <li>You are a restricted user of this website.</li>
          <li>
            You are bound not to cut, copy, distribute, modify, recreate,
            reverse engineer, distribute, disseminate, post, publish or create
            derivative works from, transfer, or sell any information or software
            obtained from the website. With our prior permission limited use may
            be allowed for the removal of doubt, it is clarified that unlimited
            or wholesale reproduction, copying of the content for commercial or
            non-commercial purposes and unwarranted modification of data and
            information within the content of the Website is not permitted.
          </li>
          <li>
            You agree not to access (or attempt to access) the Website and/or
            the materials or Services by any means other than through the
            interface that is provided by the website. The use of deep-link,
            robot, spider or other automatic device, program, algorithm or
            methodology, or any similar or equivalent manual process, to access,
            acquire, copy or monitor any portion of the Website or Content, or
            in any way reproduce or circumvent the navigational structure or
            presentation of the Website, materials or any Content, to obtain or
            attempt to obtain any materials, documents or information through
            any means not specifically made available through the Website. You
            acknowledge and agree that by accessing or using the Website or
            Services, You may be exposed to content from other users that You
            may consider offensive, indecent or otherwise objectionable. We
            disclaim all liabilities arising in relation to such offensive
            content on the Website. Further, You may report such offensive
            content to us at{' '}
            <a href="mailto:support@justmyroots.com">support@justmyroots.com</a>
          </li>
          <li>
            In places where this website allows you to post or upload
            data/information, You undertake to ensure that such material is not
            offensive and in accordance with applicable laws. Further, You
            undertake not to:
          </li>
        </ul>
        <ul className="roman">
          <li>
            Abuse, harass, threaten, defame, disillusion, erode, abrogate,
            demean or otherwise violate the legal rights of others;
          </li>
          <li>
            Engage in any activity that interferes with or disrupts access to
            the Website or the Services (or the servers and networks which are
            connected to the Website);
          </li>
          <li>
            Impersonate any person or entity, or falsely state or otherwise
            misrepresent Your affiliation with a person or entity;
          </li>
          <li>
            Publish, post, disseminate, any information which is grossly
            harmful, harassing, blasphemous, defamatory, obscene, pornographic,
            paedophilic, libellous, invasive of another&#39;s privacy, hateful,
            or racially, ethnically objectionable, disparaging, relating
            encouraging money laundering or gambling, or otherwise unlawful in
            any manner whatever; or unlawfully threatening or unlawfully
            harassing including but not limited to &quot;indecent representation
            of women&quot; within the meaning of the Indecent Representation of
            Women (Prohibition) Act, 1986;
          </li>
          <li>
            Post any file that infringes the copyright, patent or trademark of
            other legal entities;
          </li>
          <li>
            Upload or distribute files that contain viruses, corrupted files, or
            any other similar software or programs that may damage the operation
            of the Website or another&#39;s computer;
          </li>
          <li>
            Download any file posted by another user of a Service that you know,
            or reasonably should know, cannot be legally distributed in such
            manner;
          </li>
          <li>
            Probe, scan or test the vulnerability of the Website or any network
            connected to the Website, nor breach the security or authentication
            measures on the Website or any network connected to the Website. You
            may not reverse look-up, trace or seek to trace any information on
            any other user, of or visitor to, the Website, or any other customer
            of the website, including any website Account not owned by You, to
            its source, or exploit the Website or Service or information made
            available or offered by or through the Website, in any way whether
            or not the purpose is to reveal any information, including but not
            limited to personal identification information, other than Your own
            information, as provided for by the Website;
          </li>
          <li>
            Disrupt or interfere with the security of, or otherwise cause harm
            to, the Website, systems resources, accounts, passwords, servers or
            networks connected to or accessible through the Websites or any
            affiliated or linked sites;
          </li>
          <li>
            Collect or store data about other users in connection with the
            prohibited conduct and activities set forth in this Section;
          </li>
          <li>
            Use the Website or any material or Content for any purpose that is
            unlawful or prohibited by these Terms of Use, or to solicit the
            performance of any illegal activity or other activity which
            infringes the rights of this website or other third parties;
          </li>
          <li>
            Violate any code of conduct or other guidelines, which may be
            applicable for or to any particular Service;
          </li>
          <li>
            {' '}
            Violate any applicable laws or regulations for the time being in
            force within or outside India;
          </li>
          <li>
            Violate the Terms of Use including but not limited to any applicable
            Additional Terms of the Website contained herein or elsewhere;
          </li>
          <li>
            Violate any code of conduct or other guidelines, which may be
            applicable for or to any particular Service;
          </li>
          <li>
            {' '}
            Threatens the unity, integrity, defence, security or sovereignty of
            India, friendly relations with foreign states, or public order or
            causes incitement to the commission of any cognizable offence or
            prevents investigation of any offence or is insulting any other
            nation;
          </li>
          <li>
            Publish, post, disseminate information that is false, inaccurate or
            misleading; violate any applicable laws or regulations for the time
            being in force in or outside India;
          </li>
          <li>
            Directly or indirectly, offer, attempt to offer, trade or attempt to
            trade in any item, the dealing of which is prohibited or restricted
            in any manner under the provisions of any applicable law, rule,
            regulation or guideline for the time being in force. xix. Create
            liability for Us or cause Us to lose (in whole or in part) the
            services of Our Internet Service Provider (&quot;ISPs&quot;) or
            other suppliers;
          </li>
        </ul>
        <p>
          You may not transmit any chain letters or unsolicited commercial or
          junk email to other Users via the Website. It shall be a violation of
          these Terms of Use to use any information obtained from the Website in
          order to harass, abuse, or harm another person, or in order to
          contact, advertise to, solicit, or sell to another person other than
          Us without Our prior explicit consent. We can (and You hereby
          expressly authorize Us to) disclose any information about You to law
          enforcement or other government officials, as we, in Our sole
          discretion, believe necessary or appropriate in connection with the
          investigation and/or resolution of possible crimes, especially those
          that may involve personal injury. In order to protect Our Users from
          such advertising or solicitation, We reserve the right to restrict the
          number of messages or emails which a user may send to other Users in
          any 24-hour period which We deems appropriate in its sole discretion.
          You understand that We have the right at all times to disclose any
          information (including the identity of the persons providing
          information or materials on the Website) as necessary to satisfy any
          law, regulation or valid governmental request. This may include,
          without limitation, disclosure of the information in connection with
          investigation of alleged illegal activity or solicitation of illegal
          activity or in response to a lawful court order or subpoena.
        </p>
        <h3>User content on the website</h3>
        <p>
          We have no obligation to monitor the materials posted on the Website
          including any articles published by You. We shall have the right to
          remove or edit any content that in its sole discretion violates, or is
          alleged to violate, any applicable law or either the spirit or letter
          of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY
          RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE.
          In no event shall We assume or have any responsibility or liability
          for any Content posted or for any claims, damages or losses resulting
          from use of Content and/or appearance of Content on the Website. You
          hereby represent and warrant that You have all necessary rights in and
          to all Content which You provide and all information it contains and
          that such Content shall not infringe any proprietary or other rights
          of third parties or contain any libellous, tortuous, or otherwise
          unlawful information.
        </p>
        <h3>Disclaimers</h3>
        <p>
          By using JustMyRoots Services you agree to the following disclaimers:
        </p>
        <ul className="number">
          <li>
            JustMyRoots is based on marketplace model and does not take any
            responsibility of the quality, taste and freshness of the
            comestibles. Users of this Website understand and agree that any
            order placed by them is done at their own discretion and
            responsibility and they will be solely responsible for the same.
          </li>
          <li>
            The Content on these Services is for informational purposes only.
            JMR disclaims any liability for any information that may have become
            outdated since the last time the particular piece of information was
            updated.
          </li>
          <li>
            JMR reserves the right to make changes and corrections to any part
            of the Content on these Services at any time without prior notice.
          </li>
          <li>
            JMR does not guarantee the prices listed in menus or the
            availability of all menu items at any restaurant. Unless stated
            otherwise, all pictures and information contained on these Services
            are believed to be owned by or licensed to JMR. The Pictures are
            only for representation purpose, manufacturer reserves the right and
            the shape, size and the content of the product can change without
            prior information. However, JMR takes the special effort to ensure
            that the product reaches in the right condition.
          </li>

          <li>
            Please email a takedown request (by using the &quot;Contact Us&quot;
            link on the home page) to the webmaster if you are the copyright
            owner of any Content on these Services and you think the use of the
            above material violates Your copyright in any way. Please indicate
            the exact URL of the webpage in your request. All images shown here
            have been digitized by JMR. No other party is authorized to
            reproduce or republish these digital versions in any format
            whatsoever without the prior written permission of
          </li>
          <li>
            Any certification, licenses or permits (&quot;Certification&quot;)
            or information in regard to such Certification that may be displayed
            on the Restaurant&#39;s listing page on the Platform is
            informational purposes only. Such Certification is displayed by JMR
            on an &#39;as available&#39; basis that is provided to JMR by the
            Restaurant partner(s). JMR does not make any warranties about the
            validity, authenticity, reliability and accuracy of such
            Certification or any information displayed in this regard. Any
            reliance by a user upon the Certification or information thereto
            shall be strictly at such user&#39;s own risk and JMR in no manner
            shall assume any liability whatsoever for any losses or damages in
            connection with the use of this information or for any inaccuracy,
            invalidity or discrepancy in the Certification or non-compliance of
            any applicable local laws or regulations by the Restaurant partner.
          </li>
          <li>
            Due to some technical issue, typographical error or product
            information published, Pricing on any product(s) as is reflected on
            the Website by seller may be incorrectly reflected and in such an
            event seller may cancel such your order(s).
          </li>
        </ul>
        <h3>Shipping and Delivery Policy</h3>
        <ul className="dot">
          <li>
            JMR uses special food grade packaging for all their packaging
            requirements.
          </li>
          <li>
            Our Perishable products are packaged in industry benchmarked
            packaging materials and are imported from European countries which
            follows the stringent of processes and policies.
          </li>
          <li>
            Orders placed before 11am from any Tier-1 or Metro city that are to
            be delivered to another Tier-1 or Metro city would reach its
            consumers within 24 hours or on the next day of placing the order.
            However, orders placed from any tier-2 cities, before 11am, would
            take 24-48 hours to reach its consumers.{' '}
          </li>
          <li>
            Once received, the Customers are required to heat or consume the
            products as per the product requirements, before consuming. Under no
            condition JustMyRoots shall be liable for the quality and taste of
            the food that is delivered to you.
          </li>
        </ul>
        <h3>Payment</h3>
        <ul className="dot">
          <li>
            You understand that the contract is a bipartite contract between You
            and JMR using the Payment Facility, and You shall pay the
            Transaction Price through Your Issuing Bank to JMR using Payment
            Facility.
          </li>
          <li>
            JMR uses secured 3rd Party gateways and does not hold/save any
            credit or debit or banking information.
          </li>
          <li>
            Any extension / increase in the Dispatch and/or Delivery time and
            the Transaction between you and JMR shall stand amended to such
            extent. Any such extension / increase of Dispatch / Delivery time or
            subsequent novation / variation of the Transaction should be in
            compliance with Payment Facility Rules and Policies.
          </li>
          <li>
            You, as a Buyer, shall electronically notify Payment Facility using
            the appropriate Website features immediately upon Delivery or
            non-Delivery within the time period as provided in Policies. No
            notification by You of Delivery or non-Delivery within the time
            period specified in the Policies shall be construed as a deemed
            Delivery in respect of that Transaction. JMR does not provide Cash
            on Delivery services to its Users.
          </li>
          <li>
            As a Buyer, You shall be entitled to claim a return or refund of the
            Transaction only as per the Return and Refund Policy available on
            the Website. Such refund is time barred and in case you do not raise
            a refund claim using Website features within the stipulated time
            than this would make You ineligible for a refund.
          </li>
          <li>
            You, as a Buyer, understand that the Payment Facility may not be
            available in full or in part for certain category of products and/or
            services and/or Transactions as mentioned in the Policies and hence
            You may not be entitled to a refund in respect of the Transactions
            for those products and /or services.
          </li>
        </ul>
        <h3>Cancellation and refund policy</h3>
        <ul className="dot">
          {/* <li>
            {' '}
            You cannot cancel an Order once the Restaurant has provided its
            confirmation.
          </li> */}
          <li>
            In the event You have provided incorrect particulars, e.g., contact
            number, delivery address etc., or that You were unresponsive, not
            reachable or unavailable for fulfilment of the services offered to
            You, You will not be eligible for any refunds.
          </li>
          <li>
            No replacement / refund / or any other resolution will be provided
            without documentary evidence.
          </li>
          <li>
            Any complaint, with respect to the Order which shall include
            instances but not be limited to food spillage, foreign object in
            food, delivery of the wrong order, You will be required to share the
            proof of the same before any resolution can be provided within 2
            hours of receiving the delivery of the order.
          </li>
          <li>
            You shall not be entitled to a refund in case instructions placed
            along with the Order are not followed in the form and manner You had
            intended. Instructions are followed by the Restaurant on a
            best-efforts basis.
          </li>
          <li>
            All refunds shall be processed in the form of Loyalty Points unless
            exceptions allowed by JMR.{' '}
          </li>
          {/* <li>
            If you request to cancel your order, in special circumstances we at our sole discretion may accept to cancel your order by deducting 5% of your order value as cancellation charges.{' '}
          </li> */}
        </ul>
        <h3>Cash on Delivery</h3>
        <p>We do not accept payment via Cash on Delivery.</p>
        <h3>Loyalty Points</h3>
        <p>
          All Registered customers automatically become a part of the Elite
          Loyalty points program of JMR. 2% of the total Invoice amount
          is added as Loyalty Points bonus for the customer which can be
          utilised by the Customer in future purchases.
        </p>
        <h3>Third party information</h3>
        <p>
          All text, graphics, user interfaces, visual interfaces, photographs,
          trademarks, logos, sounds, music and artwork (collectively,
          &quot;Content&quot;), is a third party user generated content and We
          have no control over such third party user generated content as We are
          merely an intermediary for the purposes of this Terms of Use. Other
          than when provided for, the use of such content and it being
          reproduced, republished, uploaded, posted, publicly displayed,
          encoded, translated, transmitted or distributed in any way (including
          &quot;mirroring&quot;) to any other computer, server, Website or other
          medium for publication or distribution or for any commercial
          enterprise, without Our express prior written consent is not allowed.
          The content that you post will become Our property and You grant Us
          the worldwide, perpetual and transferable rights in such Content. We
          shall be entitled to, consistent with Our Privacy Policy as adopted in
          accordance with applicable law, use the Content or any of its elements
          for any type of use forever, including but not limited to promotional
          and advertising purposes and in any media whether now known or
          hereafter devised, including the creation of derivative works that may
          include the Content You provide and are not entitled to any payment or
          other compensation for such use.
        </p>
        <h3>Data provided by us</h3>
        <ul className="dot">
          <li>
            From time to time, Our team may post comments or articles. These
            articles are the Intellectual Property of the Company and you are
            prohibited from posting, re producing, publishing, changing, editing
            such articles. In the case that You have a problem with any article
            so posted, you may report the same via mail and we will look into
            it. We are under no obligation to remove such articles and the final
            decision lies with us.
          </li>
          <li>
            We do not provide legal, professional advice of any sort. You are
            not obligated to any advice provided and are advised to seek
            professional advice before proceeding with any action. We absolve
            yourself of any liability arising from your actions, and you are
            solely responsible for your actions.
          </li>
          <li>
            We take utmost care to ensure that data provided at our Website is
            true and accurate. Sometimes, system errors creep in and data
            generated by other Users may be false. We are not responsible for
            any such data.
          </li>
          <li>
            We are not in any way liable to You, for any loss arising to you
            from activities that include but are not limited to our negligence,
            breach of contract, IP and trademark infringement, breach of laws,
            etc.
          </li>
          <li>
            From time to time, our Website with have external links connected to
            other websites. We in no way endorse these websites. We are in no
            way liable for the information found on those websites. External
            websites may have their own policies and we in no way are
            responsible for any loss or damage cause by the same to you. You are
            advised to use your own discretion in the navigation and use of
            external sites.
          </li>
        </ul>
        <h3>Indemnification and limitation of liability</h3>
        <p>
          You agree to indemnify, defend and hold harmless this website
          including but not limited to its affiliate vendors, agents and
          employees from and against any and all losses, liabilities, claims,
          damages, demands, costs and expenses (including legal fees and
          disbursements in connection therewith and interest chargeable thereon)
          asserted against or incurred by us that arise out of, result from, or
          may be payable by virtue of, any breach or non-performance of
          representation, warranty, covenant or agreement made or obligation to
          be performed by you pursuant to these terms of use. Further, you agree
          to hold us harmless against any claims made by any third party due to,
          or arising out of, or in connection with, your use of the website, any
          claim that your material caused damage to a third party, your
          violation of the terms of use, or your violation of any rights of
          another, including any intellectual property rights.
        </p>
        <p>
          In no event shall JMR, its officers, directors, employees, partners or
          suppliers be liable to you, the vendor or any third party for any
          special, incidental, indirect, consequential or punitive damages
          whatsoever, including those resulting from loss of use, data or
          profits, whether or not foreseeable or whether or not we have been
          advised of the possibility of such damages, or based on any theory of
          liability, including breach of contract or warranty, negligence or
          other tortious action, or any other claim arising out of or in
          connection with your use of or access to the website, services or
          materials.
        </p>
        <p>
          The limitations and exclusions in this section apply to the maximum
          extent permitted by applicable law
        </p>
        <h3>Compliance with laws</h3>
        <p>
          It is expressly agreed to by the Parties hereto that the formation,
          interpretation and performance of these Terms and any disputes arising
          here from will be resolved through a two-step Alternate Dispute
          Resolution (“ADR”) mechanism. It is further agreed to by the Parties
          that the contents of this Clause shall survive even after the
          termination or expiry of the Terms and/or Policy.
        </p>
        <ul className="dot">
          <li>
            Mediation: In case of any dispute between the parties, the Parties
            will attempt to resolve the same amicably amongst themselves, to the
            mutual satisfaction of both Parties. In the event that the Parties
            are unable to reach such an amicable solution within thirty (30)
            days of one Party communicating the existence of a dispute to the
            other Party, the dispute will be resolved by arbitration, as
            detailed herein below;
          </li>
          <li>
            Arbitration. In the event that the Parties are unable to amicably
            resolve a dispute by mediation, said dispute will be referred to
            arbitration by a sole arbitrator to be appointed by the Company, and
            the award passed by such sole arbitrator will be valid and binding
            on both Parties. The Parties shall bear their own costs for the
            proceedings, although the sole arbitrator may, in his/her sole
            discretion, direct either Party to bear the entire cost of the
            proceedings. The arbitration shall be conducted in English, and the
            seat of Arbitration shall be the city of Gurugram.
          </li>
        </ul>
        <p>
          The Parties expressly agree that the Terms, Policy and any other
          agreements entered into between the Parties are governed by the laws,
          rules and regulations of India, and that the Courts at Haryana shall
          have exclusive jurisdiction over any disputes arising between the
          Parties.
        </p>
        <h3>Miscellaneous provision</h3>
        <ul className="dot">
          <li>
            Entire Agreement: This Agreement is the complete and exclusive
            statement of the agreements between You and Us with respect to the
            subject matter hereof and supersedes all other communications or
            representations or agreements (whether oral, written or otherwise)
            relating thereto.
          </li>
          <li>
            Waiver: The failure of either party at any time to require
            performance of any provision of this Agreement in no manner shall
            affect such party&#39;s right at a later time to enforce the same.
            No waiver by either party of any breach of this Agreement, whether
            by conduct or otherwise, in any one or more instances, shall be
            deemed to be, or construed as, a further or continuing waiver of any
            other such breach, or a waiver of any other breach of this
            Agreement.
          </li>
          <li>
            Severability: If any provision of this Agreement shall to any extent
            be held invalid, illegal or unenforceable, the validity, legality
            and enforceability of the remaining provisions of this Agreement
            shall in no way be affected or impaired thereby and each provision
            of this Agreement shall be valid and enforceable to the fullest
            extent permitted by law. In such case, this Agreement shall be
            reformed to the minimum extent necessary to correct any invalidity,
            illegality or unenforceability, while preserving to the maximum
            extent the rights and commercial expectations of the parties hereto,
            as expressed herein.
          </li>
        </ul>
        <h3> Account Deletion & Data Erasure </h3>
        <p>
          If you wish to delete your account with us or erase sensitive information, you may send us an email to the effect at care@justmyroots.com mentioning your relevant account information and we shall process the request on our end. We shall send you a confirmation email once your account and/or data is permanently deleted from our system.
        </p>
      </div>
    </div>
  );
};

export default Terms;
